#ifndef OTA_WEB_UI_H
#define OTA_WEB_UI_H

// Minified HTML for OTA web interface
// Source: ota_ui.html
static const char ota_html[] =
"<!DOCTYPE html>"
"<html lang=\"en\">"
"<head>"
"<meta charset=\"UTF-8\">"
"<meta name=\"viewport\" content=\"width=device-width,initial-scale=1.0\">"
"<title>Serial WiFi Logger - OTA Update</title>"
"<style>"
"*{margin:0;padding:0;box-sizing:border-box}"
"body{font-family:-apple-system,BlinkMacSystemFont,\"Segoe UI\",Arial,sans-serif;max-width:600px;margin:0 auto;padding:20px;background:#f5f5f5}"
"h1{color:#333;margin-bottom:20px;font-size:24px}"
"h2{color:#555;margin-top:30px;margin-bottom:15px;font-size:18px}"
".info-box{background:#fff;padding:15px;border-radius:8px;margin-bottom:20px;box-shadow:0 2px 4px rgba(0,0,0,0.1)}"
".info-row{display:flex;justify-content:space-between;padding:8px 0;border-bottom:1px solid #eee}"
".info-row:last-child{border-bottom:none}"
".info-label{font-weight:600;color:#666}"
".info-value{color:#333;font-family:monospace}"
".upload-section{background:#fff;padding:20px;border-radius:8px;box-shadow:0 2px 4px rgba(0,0,0,0.1)}"
"input[type=\"file\"]{display:block;width:100%;padding:10px;margin-bottom:15px;border:2px dashed #ccc;border-radius:4px;cursor:pointer}"
"input[type=\"file\"]:hover{border-color:#999}"
"button{width:100%;padding:12px;background:#007bff;color:white;border:none;border-radius:4px;font-size:16px;cursor:pointer;transition:background 0.3s}"
"button:hover:not(:disabled){background:#0056b3}"
"button:disabled{background:#ccc;cursor:not-allowed}"
"progress{width:100%;height:30px;margin:15px 0;border-radius:4px;overflow:hidden}"
"progress::-webkit-progress-bar{background:#f0f0f0;border-radius:4px}"
"progress::-webkit-progress-value{background:#28a745;border-radius:4px}"
".status-message{margin-top:15px;padding:12px;border-radius:4px;display:none}"
".status-message.show{display:block}"
".status-success{background:#d4edda;color:#155724;border:1px solid #c3e6cb}"
".status-error{background:#f8d7da;color:#721c24;border:1px solid #f5c6cb}"
".status-info{background:#d1ecf1;color:#0c5460;border:1px solid #bee5eb}"
".hidden{display:none}"
"</style>"
"</head>"
"<body>"
"<h1>Serial WiFi Logger - OTA Update</h1>"
"<div class=\"info-box\">"
"<div class=\"info-row\"><span class=\"info-label\">Firmware Version:</span><span class=\"info-value\" id=\"version\">Loading...</span></div>"
"<div class=\"info-row\"><span class=\"info-label\">Running Partition:</span><span class=\"info-value\" id=\"partition\">Loading...</span></div>"
"<div class=\"info-row\"><span class=\"info-label\">Uptime:</span><span class=\"info-value\" id=\"uptime\">Loading...</span></div>"
"</div>"
"<div class=\"upload-section\">"
"<h2>Upload Firmware</h2>"
"<input type=\"file\" id=\"fileInput\" accept=\".bin\"/>"
"<button id=\"uploadBtn\" onclick=\"uploadFirmware()\">Upload Firmware</button>"
"<progress id=\"progressBar\" value=\"0\" max=\"100\" class=\"hidden\"></progress>"
"<div id=\"statusMessage\" class=\"status-message\"></div>"
"</div>"
"<script>"
"fetch('/api/info').then(r=>r.json()).then(d=>{"
"document.getElementById('version').textContent=d.version||'Unknown';"
"document.getElementById('partition').textContent=d.partition||'Unknown';"
"document.getElementById('uptime').textContent=(d.uptime||0)+' seconds';"
"}).catch(e=>{"
"console.error('Failed to fetch device info:',e);"
"document.getElementById('version').textContent='Error';"
"document.getElementById('partition').textContent='Error';"
"document.getElementById('uptime').textContent='Error';"
"});"
"function showStatus(m,t){"
"const s=document.getElementById('statusMessage');"
"s.textContent=m;s.className='status-message show status-'+t"
"}"
"function uploadFirmware(){"
"const fi=document.getElementById('fileInput'),"
"ub=document.getElementById('uploadBtn'),"
"pb=document.getElementById('progressBar'),"
"f=fi.files[0];"
"if(!f){showStatus('Please select a firmware file (.bin)','error');return}"
"if(!f.name.endsWith('.bin')){showStatus('Invalid file type. Please select a .bin file','error');return}"
"ub.disabled=true;pb.classList.remove('hidden');pb.value=0;"
"showStatus('Uploading firmware...','info');"
"const x=new XMLHttpRequest();"
"x.upload.onprogress=e=>{if(e.lengthComputable)pb.value=(e.loaded/e.total)*100};"
"x.onload=()=>{"
"if(x.status===200){"
"pb.value=100;"
"showStatus('Firmware uploaded successfully! Device will reboot in 3 seconds...','success');"
"fi.disabled=true"
"}else{"
"ub.disabled=false;"
"showStatus('Upload failed: '+x.responseText,'error')"
"}"
"};"
"x.onerror=()=>{"
"ub.disabled=false;pb.classList.add('hidden');"
"showStatus('Upload failed: Network error','error')"
"};"
"x.open('POST','/api/ota');"
"x.setRequestHeader('Content-Type','application/octet-stream');"
"x.send(f)"
"}"
"document.getElementById('fileInput').addEventListener('change',function(){"
"document.getElementById('uploadBtn').disabled=!this.files[0]"
"});"
"</script>"
"</body>"
"</html>";

#endif // OTA_WEB_UI_H
