#ifndef OTA_WEB_UI_H
#define OTA_WEB_UI_H

/* Embedded HTML for the device's web UI: status overview, Tailscale config,
 * WireGuard config, and the OTA firmware uploader. Kept as one C string
 * literal so it can be served directly without a filesystem mount. */
static const char ota_html[] =
"<!DOCTYPE html>"
"<html lang=\"en\">"
"<head>"
"<meta charset=\"UTF-8\">"
"<meta name=\"viewport\" content=\"width=device-width,initial-scale=1.0\">"
"<title>Serial WiFi Logger</title>"
"<style>"
"*{margin:0;padding:0;box-sizing:border-box}"
"body{font-family:-apple-system,BlinkMacSystemFont,\"Segoe UI\",Arial,sans-serif;max-width:720px;margin:0 auto;padding:20px;background:#f5f5f5;color:#333}"
"h1{margin-bottom:18px;font-size:22px}"
"h2{margin-top:18px;margin-bottom:12px;font-size:17px;color:#555}"
".tabs{display:flex;border-bottom:2px solid #dfdfdf;margin-bottom:18px;overflow-x:auto}"
".tab{padding:10px 16px;cursor:pointer;border:none;background:transparent;font-size:14px;color:#666;white-space:nowrap}"
".tab.active{color:#007bff;border-bottom:2px solid #007bff;margin-bottom:-2px;font-weight:600}"
".panel{display:none;background:#fff;padding:18px;border-radius:8px;box-shadow:0 2px 4px rgba(0,0,0,0.08)}"
".panel.active{display:block}"
".row{display:flex;justify-content:space-between;align-items:center;padding:8px 0;border-bottom:1px solid #eee}"
".row:last-child{border-bottom:none}"
".lbl{font-weight:600;color:#666;margin-right:12px}"
".val{font-family:monospace;color:#333;text-align:right;word-break:break-all}"
".val.bad{color:#c0392b}"
".val.good{color:#0d8a3a}"
"label.field{display:block;margin-bottom:12px;font-size:14px;color:#555}"
"label.field>span{display:block;font-weight:600;margin-bottom:4px}"
"input[type=text],input[type=password],input[type=number]{width:100%;padding:8px 10px;border:1px solid #ccc;border-radius:4px;font-size:14px;font-family:inherit}"
"input[type=checkbox]{margin-right:8px;transform:scale(1.2)}"
"input[type=file]{display:block;width:100%;padding:10px;margin-bottom:14px;border:2px dashed #ccc;border-radius:4px;cursor:pointer}"
"button{padding:10px 18px;background:#007bff;color:#fff;border:none;border-radius:4px;font-size:14px;cursor:pointer;margin-top:6px}"
"button:hover:not(:disabled){background:#0056b3}"
"button:disabled{background:#ccc;cursor:not-allowed}"
"button.secondary{background:#6c757d}"
"button.secondary:hover:not(:disabled){background:#545b62}"
"progress{width:100%;height:24px;margin:12px 0;border-radius:4px;overflow:hidden}"
".msg{margin-top:12px;padding:10px;border-radius:4px;display:none;font-size:14px}"
".msg.show{display:block}"
".msg.ok{background:#d4edda;color:#155724;border:1px solid #c3e6cb}"
".msg.err{background:#f8d7da;color:#721c24;border:1px solid #f5c6cb}"
".msg.info{background:#d1ecf1;color:#0c5460;border:1px solid #bee5eb}"
".hint{font-size:12px;color:#888;margin-top:-8px;margin-bottom:10px}"
".hidden{display:none}"
"</style>"
"</head>"
"<body>"
"<h1>Serial WiFi Logger</h1>"
"<div class=\"tabs\">"
"<button class=\"tab active\" data-panel=\"status\">Status</button>"
"<button class=\"tab\" data-panel=\"tailscale\">Tailscale</button>"
"<button class=\"tab\" data-panel=\"wireguard\">WireGuard</button>"
"<button class=\"tab\" data-panel=\"ota\">OTA</button>"
"</div>"

/* ---------- Status panel ---------- */
"<div class=\"panel active\" id=\"panel-status\">"
"<div class=\"row\"><span class=\"lbl\">Firmware</span><span class=\"val\" id=\"s-version\">—</span></div>"
"<div class=\"row\"><span class=\"lbl\">Partition</span><span class=\"val\" id=\"s-partition\">—</span></div>"
"<div class=\"row\"><span class=\"lbl\">Uptime</span><span class=\"val\" id=\"s-uptime\">—</span></div>"
"<div class=\"row\"><span class=\"lbl\">WiFi IP</span><span class=\"val\" id=\"s-wifi\">—</span></div>"
"<div class=\"row\"><span class=\"lbl\">Tailscale</span><span class=\"val\" id=\"s-ts\">—</span></div>"
"<div class=\"row\"><span class=\"lbl\">WireGuard</span><span class=\"val\" id=\"s-wg\">—</span></div>"
"<button class=\"secondary\" onclick=\"refreshStatus()\">Refresh</button>"
"</div>"

/* ---------- Tailscale panel ---------- */
"<div class=\"panel\" id=\"panel-tailscale\">"
"<div class=\"msg info\" id=\"ts-auth-url-box\" style=\"display:none\">"
"<strong>Approval required.</strong> Open this URL in a browser signed in to your tailnet to approve this device:<br><a id=\"ts-auth-url\" target=\"_blank\" rel=\"noopener\"></a>"
"</div>"
"<label class=\"field\"><input type=\"checkbox\" id=\"ts-enabled\"><span style=\"display:inline\">Enable Tailscale (mutually exclusive with WireGuard)</span></label>"
"<label class=\"field\"><span>Hostname</span><input type=\"text\" id=\"ts-hostname\" placeholder=\"esp32-serial\"></label>"
"<label class=\"field\"><span>Control Server</span><input type=\"text\" id=\"ts-control\" placeholder=\"login.tailscale.com\"></label>"
"<label class=\"field\"><span>Auth Key (tskey-auth-…)</span><input type=\"password\" id=\"ts-auth\" placeholder=\"leave blank to keep existing\"></label>"
"<div class=\"hint\" id=\"ts-auth-hint\"></div>"
"<button onclick=\"saveTailscale()\">Save &amp; Apply</button>"
"<div class=\"msg\" id=\"ts-msg\"></div>"
"</div>"

/* ---------- WireGuard panel ---------- */
"<div class=\"panel\" id=\"panel-wireguard\">"
"<label class=\"field\"><input type=\"checkbox\" id=\"wg-enabled\"><span style=\"display:inline\">Enable WireGuard (manual mode)</span></label>"
"<label class=\"field\"><span>Local IP</span><input type=\"text\" id=\"wg-localip\"></label>"
"<label class=\"field\"><span>Local Netmask</span><input type=\"text\" id=\"wg-netmask\"></label>"
"<label class=\"field\"><span>Local Gateway (optional)</span><input type=\"text\" id=\"wg-gateway\"></label>"
"<label class=\"field\"><span>Private Key (base64)</span><input type=\"password\" id=\"wg-priv\" placeholder=\"leave blank to keep existing\"></label>"
"<div class=\"hint\" id=\"wg-priv-hint\"></div>"
"<label class=\"field\"><span>Peer Public Key</span><input type=\"text\" id=\"wg-peerpub\"></label>"
"<label class=\"field\"><span>Peer Endpoint (host)</span><input type=\"text\" id=\"wg-peerep\"></label>"
"<label class=\"field\"><span>Peer Port</span><input type=\"number\" id=\"wg-peerport\" min=\"1\" max=\"65535\"></label>"
"<label class=\"field\"><span>Listen Port</span><input type=\"number\" id=\"wg-listen\" min=\"0\" max=\"65535\"></label>"
"<label class=\"field\"><span>Keepalive (s)</span><input type=\"number\" id=\"wg-ka\" min=\"0\" max=\"3600\"></label>"
"<label class=\"field\"><input type=\"checkbox\" id=\"wg-default\"><span style=\"display:inline\">Set as default route</span></label>"
"<label class=\"field\"><span>NTP Server</span><input type=\"text\" id=\"wg-ntp\"></label>"
"<label class=\"field\"><span>Pre-Shared Key (64 hex chars, optional; blank = none)</span><input type=\"password\" id=\"wg-psk\" placeholder=\"leave blank to keep existing\"></label>"
"<div class=\"hint\" id=\"wg-psk-hint\"></div>"
"<button onclick=\"saveWireGuard()\">Save &amp; Apply</button>"
"<div class=\"msg\" id=\"wg-msg\"></div>"
"</div>"

/* ---------- OTA panel (existing) ---------- */
"<div class=\"panel\" id=\"panel-ota\">"
"<input type=\"file\" id=\"otaFile\" accept=\".bin\"/>"
"<button id=\"otaBtn\" onclick=\"uploadFirmware()\" disabled>Upload Firmware</button>"
"<progress id=\"otaProgress\" value=\"0\" max=\"100\" class=\"hidden\"></progress>"
"<div class=\"msg\" id=\"otaMsg\"></div>"
"</div>"

"<script>"
/* ----- Tab switcher ----- */
"document.querySelectorAll('.tab').forEach(t=>{"
"t.addEventListener('click',()=>{"
"document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));"
"document.querySelectorAll('.panel').forEach(x=>x.classList.remove('active'));"
"t.classList.add('active');"
"document.getElementById('panel-'+t.dataset.panel).classList.add('active')"
"})"
"});"

/* ----- Helpers ----- */
"function $(id){return document.getElementById(id)}"
"function setMsg(id,text,kind){var e=$(id);if(!e)return;e.textContent=text;e.className='msg show '+kind}"
"function clearMsg(id){var e=$(id);if(!e)return;e.className='msg'}"
"async function getJSON(u){var r=await fetch(u);if(!r.ok)throw new Error(u+' '+r.status);return r.json()}"
"async function putJSON(u,b){var r=await fetch(u,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)});var t=await r.text();var j;try{j=JSON.parse(t)}catch(e){j={raw:t}}return{ok:r.ok,status:r.status,body:j}}"

/* ----- Status panel ----- */
"async function refreshStatus(){"
"try{"
"var info=await getJSON('/api/info');"
"$('s-version').textContent=info.version||'—';"
"$('s-partition').textContent=info.partition||'—';"
"$('s-uptime').textContent=(info.uptime||0)+' s';"
"}catch(e){$('s-version').textContent='error';}"
"try{"
"var st=await getJSON('/api/network/status');"
"$('s-wifi').textContent=st.wifi.connected?st.wifi.ip:'(no link)';"
"$('s-wifi').className='val '+(st.wifi.connected?'good':'bad');"
"var ts=st.tailscale;"
"$('s-ts').textContent=(ts.enabled?'enabled':'disabled')+' / '+(ts.running?'running '+(ts.ip||'…'):'stopped');"
"$('s-ts').className='val '+(ts.running?'good':(ts.enabled?'bad':''));"
"var wg=st.wireguard;"
"$('s-wg').textContent=(wg.enabled?'enabled':'disabled')+' / '+(wg.running?'running':'stopped');"
"$('s-wg').className='val '+(wg.running?'good':(wg.enabled?'bad':''));"
"}catch(e){$('s-ts').textContent='error';}"
"}"
"refreshStatus();"

/* ----- Tailscale form ----- */
"async function loadTailscale(){"
"try{"
"var d=await getJSON('/api/tailscale');"
"$('ts-enabled').checked=!!d.enabled;"
"$('ts-hostname').value=d.hostname||'';"
"$('ts-control').value=d.control_server||'';"
"$('ts-auth-hint').textContent=d.auth_key_set?('current: '+(d.auth_key_hint||'set')):'no auth_key configured';"
"var urlBox=$('ts-auth-url-box'),urlA=$('ts-auth-url');"
"if(d.auth_url){urlA.href=d.auth_url;urlA.textContent=d.auth_url;urlBox.style.display='block'}"
"else{urlBox.style.display='none';urlA.removeAttribute('href');urlA.textContent=''}"
"}catch(e){setMsg('ts-msg','Failed to load: '+e.message,'err')}"
"}"
"async function saveTailscale(){"
"clearMsg('ts-msg');"
"var body={enabled:$('ts-enabled').checked,hostname:$('ts-hostname').value.trim(),control_server:$('ts-control').value.trim()};"
"var ak=$('ts-auth').value.trim();if(ak)body.auth_key=ak;"
"setMsg('ts-msg','Saving…','info');"
"var r=await putJSON('/api/tailscale',body);"
"if(r.ok){setMsg('ts-msg','Saved. State will update in a few seconds.','ok');$('ts-auth').value='';setTimeout(loadTailscale,2500);setTimeout(refreshStatus,3000)}"
"else setMsg('ts-msg','Error: '+(r.body.error||('HTTP '+r.status)),'err')"
"}"
"loadTailscale();"

/* ----- WireGuard form ----- */
"async function loadWireGuard(){"
"try{"
"var d=await getJSON('/api/wireguard');"
"$('wg-enabled').checked=!!d.enabled;"
"$('wg-localip').value=d.local_ip||'';"
"$('wg-netmask').value=d.local_netmask||'';"
"$('wg-gateway').value=d.local_gateway||'';"
"$('wg-peerpub').value=d.peer_pub_key||'';"
"$('wg-peerep').value=d.peer_endpoint||'';"
"$('wg-peerport').value=d.peer_port||0;"
"$('wg-listen').value=d.listen_port||0;"
"$('wg-ka').value=d.keepalive||0;"
"$('wg-default').checked=!!d.set_default;"
"$('wg-ntp').value=d.ntp_server||'';"
"$('wg-priv-hint').textContent=d.private_key_set?'private key is set on device':'no private key configured';"
"$('wg-psk-hint').textContent=d.preshared_key_set?'preshared key is set on device':'no preshared key configured';"
"}catch(e){setMsg('wg-msg','Failed to load: '+e.message,'err')}"
"}"
"async function saveWireGuard(){"
"clearMsg('wg-msg');"
"var body={"
"enabled:$('wg-enabled').checked,"
"local_ip:$('wg-localip').value.trim(),"
"local_netmask:$('wg-netmask').value.trim(),"
"local_gateway:$('wg-gateway').value.trim(),"
"peer_pub_key:$('wg-peerpub').value.trim(),"
"peer_endpoint:$('wg-peerep').value.trim(),"
"peer_port:Number($('wg-peerport').value),"
"listen_port:Number($('wg-listen').value),"
"keepalive:Number($('wg-ka').value),"
"set_default:$('wg-default').checked,"
"ntp_server:$('wg-ntp').value.trim()"
"};"
"var pv=$('wg-priv').value.trim();if(pv)body.private_key=pv;"
"var pk=$('wg-psk').value.trim();if(pk!==undefined)body.preshared_key=pk;"
"setMsg('wg-msg','Saving…','info');"
"var r=await putJSON('/api/wireguard',body);"
"if(r.ok){setMsg('wg-msg','Saved. State will update in a few seconds.','ok');$('wg-priv').value='';$('wg-psk').value='';setTimeout(loadWireGuard,2500);setTimeout(refreshStatus,3000)}"
"else setMsg('wg-msg','Error: '+(r.body.error||('HTTP '+r.status)),'err')"
"}"
"loadWireGuard();"

/* ----- OTA upload (preserved from previous version) ----- */
"$('otaFile').addEventListener('change',function(){$('otaBtn').disabled=!this.files[0]});"
"function uploadFirmware(){"
"var f=$('otaFile').files[0],pb=$('otaProgress'),mb=$('otaBtn');"
"if(!f){setMsg('otaMsg','Select a .bin file','err');return}"
"if(!f.name.endsWith('.bin')){setMsg('otaMsg','Invalid file type','err');return}"
"mb.disabled=true;pb.classList.remove('hidden');pb.value=0;setMsg('otaMsg','Uploading…','info');"
"var x=new XMLHttpRequest();"
"x.upload.onprogress=e=>{if(e.lengthComputable)pb.value=(e.loaded/e.total)*100};"
"x.onload=()=>{if(x.status===200){pb.value=100;setMsg('otaMsg','Upload OK — device rebooting','ok');$('otaFile').disabled=true}"
"else{mb.disabled=false;setMsg('otaMsg','Upload failed: '+x.responseText,'err')}};"
"x.onerror=()=>{mb.disabled=false;pb.classList.add('hidden');setMsg('otaMsg','Network error','err')};"
"x.open('POST','/api/ota');x.setRequestHeader('Content-Type','application/octet-stream');x.send(f)"
"}"
"</script>"
"</body>"
"</html>";

#endif // OTA_WEB_UI_H
